# Generated by Django 5.2.9 on 2025-12-22 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snippet",
            name="tags",
        ),
        migrations.AlterModelOptions(
            name="snippet",
            options={"ordering": ["-created_at"]},
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
